package com.dinkybell.ecommerce.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * User entity representing the main user information in the system.
 * 
 * This entity stores core user data including: - User ID (primary key) - Email (used as username) -
 * Password (encrypted) - Role (user permission level)
 * 
 * This entity is mapped to the "users" table in the database. Lombok's @Data annotation
 * automatically generates getters, setters, equals, hashCode and toString methods.
 */
@Entity
@Table(name = "users")
@Data
public class User {

    /**
     * The unique identifier for the user. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * The user's encrypted password. Should never store plain text passwords.
     */
    private String password;

    /**
     * The user's email address. Used as the username for authentication.
     */
    private String email;

    /**
     * The user's role in the system. Determines permissions and access levels.
     */
    private String role;

}
